name: 'linksafe-action'

branding:
    icon: 'check'
    color: 'purple'

description: 'Check all links and ensure they are not broken'
inputs:
  ignored_links:  # id of input
    description: 'Links to ignore even if they"re broken'
    required: false
  ignored_files:
    description: 'Files that will not be scanned'
    required: false
  ignored_dirs:
    description: 'Directories that will not be scanned'
    required: false
runs:
  using: 'composite'
  steps:
  - name: setup python
    uses: actions/setup-python@v3
    with:
      python-version: "3.9"
  - name: install dependencies
    run: pip install requests
    shell: bash
  - name: checkout repo
    uses: actions/checkout@v3
  - name: Run action
    run: |
      python3 ${{ github.action_path }}/src/scan_file.py
    env:
      INPUT_IGNORED_LINKS: ${{ inputs.IGNORED_LINKS }}
      INPUT_IGNORED_FILES: ${{ inputs.IGNORED_FILES }}
      INPUT_IGNORED_DIRS: ${{ inputs.IGNORED_DIRS }}
    shell: bash
  - name: Write summary
    if: always()
    run: |
      cat tmp.txt >> $GITHUB_STEP_SUMMARY
    shell: bash
