name: Test workflow

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Run the action
        uses: Yaraslaut/linksafe@main
        with:
          ignored_links: "https://www.iamkneel.tk/blog"
          ignored_files: "./src/scan_file.py"
          ignored_dirs: "test"
